apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: appteste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appteste
  template:
    metadata:
      labels:
        app: appteste
    spec:
      containers:
      - name: appteste
        image: appteste.azurecr.io/dockerdemo:1336
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock

  strategy:
    blueGreen:
      activeService: appteste-svc-active
      previewService: appteste-svc-preview
      autoPromotionEnabled: false